version: '3.8'

# IMPORTANT:
# To make this cluster connectable:
# On Linux:
#   add :
# 127.0.0.1 mongo0
# 127.0.0.1 mongo1
# 127.0.0.1 mongo2
#   at the end of your /etc/hosts file
# On windows:
#   switch to a real OS
#   or
#   add:
# 127.0.0.1 mongo0 127.0.0.1 mongo1 127.0.0.1 mongo2
#   at the end of your C:/Windows/System32/drivers/etc/hosts file

services:
  redis-stack:
    image: redis/redis-stack:latest
    volumes:
      - redis-stack-data:/bitnami/redis/data
    ports:
      - "8001:8001"
      - "6379:6379"
    networks:
      - redisnet


  mongo0:
    build: .
    image: mongocustom:6.0.2
    container_name: mongo0
    hostname: mongo0
    networks:
      - mongonet
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    command: "--config /etc/mongod.conf --port 27017"
    healthcheck:
      test: [ "CMD", "mongosh", "--port", "27017", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 2s
      retries: 5

  mongo1:
    build: .
    image: mongocustom:6.0.2
    container_name: mongo1
    hostname: mongo1
    networks:
      - mongonet
    ports:
      - "27018:27018"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    command: "--config /etc/mongod.conf --port 27018"
    healthcheck:
      test: [ "CMD", "mongosh", "--port", "27018", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 2s
      retries: 5

  mongo2:
    build: .
    image: mongocustom:6.0.2
    container_name: mongo2
    hostname: mongo2
    networks:
      - mongonet
    ports:
      - "27019:27019"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    command: "--config /etc/mongod.conf --port 27019"
    healthcheck:
      test: [ "CMD", "mongosh", "--port", "27019","--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 2s
      retries: 5

  mongoInit:
    build: .
    image: mongocustom:6.0.2
    hostname: mongoinit
    networks:
      - mongonet
    container_name: mongoinit
    depends_on:
      mongo0:
        condition: service_healthy
      mongo1:
        condition: service_healthy
      mongo2:
        condition: service_healthy
    command: >
      mongosh --host mongo0:27017 --username admin --password password --authenticationDatabase admin --eval
      '
      rs.initiate({
      _id: "mongo_repl",
      version: 1,
      members: [
        {_id: 0, host: "mongo0:27017", priority: 3},
        {_id: 1, host: "mongo1:27018", priority: 2},
        {_id: 2, host: "mongo2:27019", priority: 1}
      ]
      });'

volumes:
  redis-stack-data:
    driver: local

networks:
  mongonet: { }
  redisnet: { }

